### ISSUE TITLE
Bowtie Align should prevent user from incompatible .fastq pairs

### ISSUE THREAD

**Issue by RobJackson28** [chgibb/PHAT#320]
Incomptaible .fastq pairs, such as two "forward" or two "reverse" read files, or a "forward" and "reverse" read file from different pairs, should not be able to be selected. They fail in alignment, but it would be nice to have a feature that "faded out"incompatible options once one file is selected. The solution should be based on some aspect of the file content itself, rather than just the file names (as these could be arbitrary, though rarely are).

**Comment by chgibb** [comment]
This is likely impossible without context as to the file's origins. Reopen if research proves otherwise.
