### ISSUE TITLE
Fastq path issue, alignment fails

### ISSUE THREAD

**Issue by RobJackson28** [chgibb/PHAT#364]
Alignment instantaneously failed, v0.0.9, win32:
R59_S11_L001_R1_001.fastq
R59_S11_L001_R2_001.fastq
Against HPVs.fasta

From jobVerboseLog.txt:

"Warning: Could not open read file \"C:\\Users\\Rob\\Desktop\\Google Drive\\PhD\\Conferences\\Viruses 2016 Conference\\HPV analysis\\Run_MiSeq_12?15\\11_Sample RJ1 ADNg\\Raw data\\R59_S11_L001_R1_001.fastq\" for reading; skipping...\nError: No input read files were valid\n"

![image](https://user-images.githubusercontent.com/22773154/26851371-a54edc14-4ad8-11e7-8370-539f2a72cf84.png)

Invalid character issue it looks like.

Moved files to simple directory and alignment succeeded.

**Comment by chgibb** [comment]
Sufficiently old enough to close. Error handling around paths for read inputs is more robust than in the past.
