### ISSUE TITLE
Alignment- graphics fix

### ISSUE THREAD

**Issue by smashingbr** [chgibb/PHAT#504]
Make the alignment selection like the input
![image](https://user-images.githubusercontent.com/30178508/28228649-5b638a26-68ad-11e7-99f2-1ee1386d85c6.png)

So no check mark spots but selection of text. 

![image](https://user-images.githubusercontent.com/30178508/28228671-702f6e48-68ad-11e7-8763-4177f9ea1f17.png)

Could also change name on the top table to sequence names and the bottom as reference genome

**Comment by chgibb** [comment]
UI was overhauled in August.
