### ISSUE TITLE
Coverage track generation error

### ISSUE THREAD

**Issue by RobJackson28** [chgibb/PHAT#588]
win32 portable v0.1.1-beta.4 when generating and adding a coverage track onto a previously made figure

![image](https://user-images.githubusercontent.com/22773154/29079052-1aa8b0d4-7c2a-11e7-94bc-a4fca2010dc8.png)

**Comment by chgibb** [comment]
Reproduced in Debian package version 0.1.1-beta.4.

**Comment by RobJackson28** [comment]
Upon opening a previously made figure with the genome builder I received the same error. As well, received same error when trying to generate and add a coverage track.

**Comment by RobJackson28** [comment]
Appears fixed in v0.1.1-beta.7 win32 portable
