### ISSUE TITLE
Installing Image

### ISSUE THREAD

**Issue by Anirudh2017** [chgibb/PHAT#628]
The white background appears in the "installing"
![screenshot 9](https://user-images.githubusercontent.com/30705076/29586842-fe2c8990-8759-11e7-9160-b2a4cd82d9e9.png)
 image:

**Comment by RobJackson28** [comment]
@chgibb I don't see this white background issue in the GIF itself. Perhaps there is a style setting that needs to be set for transparency? If not, let me know and I'll create a square GIF

**Comment by RobJackson28** [comment]
Uploaded a new one (squared) resolve.

**Comment by Anirudh2017** [comment]
Sounds good!
