### ISSUE TITLE
Pileup Viewer Resolution

### ISSUE THREAD

**Issue by RobJackson28** [chgibb/PHAT#720]
Pileup viewer resolution appears stretched. This could be due to me using a high screen resolution (3000x2000), but thought I'd file the issue just in case it's a more wide-spread problem:

![image](https://user-images.githubusercontent.com/22773154/33735564-a07ceea4-db5d-11e7-8782-640584e40038.png)

**Comment by chgibb** [comment]
I would ask over in [Pileup.js' repo](https://github.com/hammerlab/pileup.js/) and see if this is a known issue.

**Comment by chgibb** [comment]
As far as I know this was fixed in a not so recent pileup update.
