### ISSUE TITLE
Issure with .csv output

### ISSUE THREAD

**Issue by dnygard** [chgibb/PHAT#781]
When outputting SNP table as .csv, there is no information in the Position column and the Ref and Alt columns have shifted over to fill the space.

**Comment by chgibb** [comment]
Successfully reproduced in PHAT@0.8.0. I should have some time in the next few days to whip up a fix. If this is urgent or blocking something you're doing, let me know and I'll try to get it fixed sooner.

![selection_031](https://user-images.githubusercontent.com/18079458/40076317-93c5293a-584c-11e8-8f93-0ee0ff6619b2.png)

**Comment by chgibb** [comment]
Fix is live in 0.8.1-beta.1. You can restart to update or download from [here](https://chgibb.github.io/PHATDocs/releases/0.8.1-beta.1/index).

**Comment by RobJackson28** [comment]
@dnygard Did this fix the issue?

**Comment by dnygard** [comment]
@chgibb @RobJackson28 Yes sorry I forgot to reply in this thread. Works fine now, thanks Chris.

**Comment by chgibb** [comment]
No worries. Good to hear!
